version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: routexpert-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - routexpert-network

  backend:
    build: ./backend
    container_name: routexpert-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://admin:admin123@mongo:27017/routexpert?authSource=admin
      JWT_SECRET: supersecretjwt
    depends_on:
      - mongo
    networks:
      - routexpert-network

  frontend:
    build: ./frontend
    container_name: routexpert-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - routexpert-network

networks:
  routexpert-network:
    driver: bridge

volumes:
  mongo_data:
